"""adiciona tabela de anexos financeiros

Revision ID: 4beefe74b866
Revises: f69c63fa7214
Create Date: 2026-09-11 01:57:59.994493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4beefe74b866'
down_revision: Union[str, None] = 'f69c63fa7214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anexos_financeiros',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('movimentacao_financeira_id', sa.BigInteger(), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('nome_armazenado', sa.String(length=255), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=False),
    sa.Column('enviado_por_usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enviado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['movimentacao_financeira_id'], ['movimentacoes_financeiras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_armazenado')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anexos_financeiros')
    # ### end Alembic commands ###
