"""adiciona tabela de patrimonios e permissoes do modulo

Revision ID: 8c8e37a26f1d
Revises: 2872188a448c
Create Date: 2026-09-15 10:58:13.422866

Cria a tabela `patrimonios` (tarefa 23) e semeia as 3 permissões do módulo, vinculando-as aos
perfis conforme a matriz de backend/RBAC.md. O seed é idempotente (ON CONFLICT DO NOTHING) para
rodar tanto em banco novo quanto no banco existente.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c8e37a26f1d'
down_revision: Union[str, None] = '2872188a448c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


PERMISSOES = [("patrimonio", "visualizar"), ("patrimonio", "criar"), ("patrimonio", "editar")]

# Administrador e Gestor administram o patrimônio; Financeiro apenas consulta, porque o valor
# de aquisição dos bens é informação patrimonial relevante para o financeiro, mas manter o
# cadastro não é atribuição dele. Demais perfis não recebem acesso.
MATRIZ = {
    "Administrador": [("patrimonio", a) for a in ["visualizar", "criar", "editar"]],
    "Gestor": [("patrimonio", a) for a in ["visualizar", "criar", "editar"]],
    "Financeiro": [("patrimonio", "visualizar")],
}


def _semear_permissoes(conn) -> None:
    for modulo, acao in PERMISSOES:
        conn.execute(
            sa.text(
                """
                INSERT INTO permissoes (nome, descricao, modulo, acao, ativo, created_at, updated_at)
                VALUES (:nome, :descricao, :modulo, :acao, true, now(), now())
                ON CONFLICT (nome) DO NOTHING
                """
            ),
            {
                "nome": f"{modulo}.{acao}",
                "descricao": f"Permite {acao} em {modulo}",
                "modulo": modulo,
                "acao": acao,
            },
        )

    for perfil_nome, pares in MATRIZ.items():
        for modulo, acao in pares:
            conn.execute(
                sa.text(
                    """
                    INSERT INTO perfil_permissoes (perfil_id, permissao_id, created_at)
                    SELECT p.id, pm.id, now()
                    FROM perfis p, permissoes pm
                    WHERE p.nome = :perfil_nome AND pm.modulo = :modulo AND pm.acao = :acao
                    ON CONFLICT (perfil_id, permissao_id) DO NOTHING
                    """
                ),
                {"perfil_nome": perfil_nome, "modulo": modulo, "acao": acao},
            )


def _remover_permissoes(conn) -> None:
    # Remove vínculos e permissões deste módulo (foram criados por esta migration).
    conn.execute(
        sa.text(
            """
            DELETE FROM perfil_permissoes
            USING permissoes pm
            WHERE perfil_permissoes.permissao_id = pm.id AND pm.modulo = 'patrimonio'
            """
        )
    )
    conn.execute(sa.text("DELETE FROM permissoes WHERE modulo = 'patrimonio'"))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patrimonios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('data_aquisicao', sa.Date(), nullable=True),
    sa.Column('valor_aquisicao', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('local', sa.String(length=255), nullable=True),
    sa.Column('responsavel_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['responsavel_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    # ### end Alembic commands ###

    _semear_permissoes(op.get_bind())


def downgrade() -> None:
    _remover_permissoes(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patrimonios')
    # ### end Alembic commands ###
