"""baseline: schema inicial completo com FKs, constraints e atendimentos

Revision ID: fde3b921d4fc
Revises:
Create Date: 2026-09-11 01:13:36.293152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'fde3b921d4fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Baseline completo: cria todo o schema em um banco limpo (dev/CI/produção nova).
    # No banco de desenvolvimento existente (com dados reais), esta revisão é aplicada
    # via `alembic stamp` em vez de `upgrade`, pois as tabelas já existem fisicamente
    # (ver backend/RELACIONAMENTOS.md e docs/historico/progresso-das-tarefas.md, tarefa 05).
    op.create_table('cargos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('categorias_financeiras',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('contas_financeiras',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('banco', sa.String(length=100), nullable=True),
    sa.Column('agencia', sa.String(length=20), nullable=True),
    sa.Column('numero_conta', sa.String(length=30), nullable=True),
    sa.Column('saldo_inicial', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfis',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('permissoes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('pessoas',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('rg', sa.String(length=30), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('estado_civil', sa.String(length=50), nullable=True),
    sa.Column('profissao', sa.String(length=150), nullable=True),
    sa.Column('escolaridade', sa.String(length=100), nullable=True),
    sa.Column('nome_mae', sa.String(length=150), nullable=True),
    sa.Column('nome_pai', sa.String(length=150), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('beneficiarios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pessoa_id', sa.BigInteger(), nullable=False),
    sa.Column('data_cadastro', sa.Date(), nullable=False),
    sa.Column('situacao_socioeconomica', sa.Text(), nullable=True),
    sa.Column('composicao_familiar', sa.Text(), nullable=True),
    sa.Column('renda_familiar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tamanho_familia', sa.Integer(), nullable=True),
    sa.Column('necessidades', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_encerramento', sa.Date(), nullable=True),
    sa.Column('motivo_encerramento', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pessoa_id')
    )
    op.create_table('membros',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pessoa_id', sa.BigInteger(), nullable=False),
    sa.Column('cargo_id', sa.BigInteger(), nullable=False),
    sa.Column('data_entrada', sa.Date(), nullable=False),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('motivo_saida', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pessoa_id')
    )
    op.create_table('perfil_permissoes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('perfil_id', sa.BigInteger(), nullable=False),
    sa.Column('permissao_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('perfil_id', 'permissao_id', name='uq_perfil_permissao')
    )
    op.create_table('projetos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('responsavel_id', sa.BigInteger(), nullable=True),
    sa.Column('orcamento', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('local', sa.String(length=255), nullable=True),
    sa.Column('objetivos', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['responsavel_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telefones',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pessoa_id', sa.BigInteger(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('whatsapp', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_telefones_pessoa_principal_unico', 'telefones', ['pessoa_id'], unique=True, postgresql_where=sa.text('principal = true'))
    op.create_table('usuarios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pessoa_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('pessoa_id')
    )
    op.create_table('voluntarios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pessoa_id', sa.BigInteger(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('area', sa.String(length=150), nullable=True),
    sa.Column('habilidades', sa.Text(), nullable=True),
    sa.Column('disponibilidade', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pessoa_id')
    )
    op.create_table('atendimentos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('beneficiario_id', sa.BigInteger(), nullable=False),
    sa.Column('responsavel_id', sa.BigInteger(), nullable=False),
    sa.Column('data_atendimento', sa.Date(), nullable=False),
    sa.Column('hora_atendimento', sa.Time(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['beneficiarios.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=True),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('tabela', sa.String(length=100), nullable=True),
    sa.Column('registro_id', sa.BigInteger(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('dados_anteriores', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('dados_novos', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_evento', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fim', sa.Time(), nullable=True),
    sa.Column('local', sa.String(length=255), nullable=True),
    sa.Column('responsavel_id', sa.BigInteger(), nullable=True),
    sa.Column('projeto_id', sa.BigInteger(), nullable=True),
    sa.Column('limite_participantes', sa.Integer(), nullable=True),
    sa.Column('exige_inscricao', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacoes_financeiras',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conta_financeira_id', sa.BigInteger(), nullable=False),
    sa.Column('categoria_id', sa.BigInteger(), nullable=False),
    sa.Column('projeto_id', sa.BigInteger(), nullable=True),
    sa.Column('responsavel_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_movimentacao', sa.Date(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_financeiras.id'], ),
    sa.ForeignKeyConstraint(['conta_financeira_id'], ['contas_financeiras.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projeto_voluntarios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('projeto_id', sa.BigInteger(), nullable=False),
    sa.Column('voluntario_id', sa.BigInteger(), nullable=False),
    sa.Column('funcao', sa.String(length=150), nullable=True),
    sa.Column('data_entrada', sa.Date(), nullable=True),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['voluntario_id'], ['voluntarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id', 'voluntario_id', name='uq_projeto_voluntario')
    )
    op.create_table('usuario_perfis',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('perfil_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'perfil_id', name='uq_usuario_perfil')
    )
    op.create_table('inscricoes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pessoa_id', sa.BigInteger(), nullable=False),
    sa.Column('evento_id', sa.BigInteger(), nullable=False),
    sa.Column('data_inscricao', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pessoa_id', 'evento_id', name='uq_inscricao_pessoa_evento')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscricoes')
    op.drop_table('usuario_perfis')
    op.drop_table('projeto_voluntarios')
    op.drop_table('movimentacoes_financeiras')
    op.drop_table('eventos')
    op.drop_table('auditoria')
    op.drop_table('atendimentos')
    op.drop_table('voluntarios')
    op.drop_table('usuarios')
    op.drop_index('ix_telefones_pessoa_principal_unico', table_name='telefones', postgresql_where=sa.text('principal = true'))
    op.drop_table('telefones')
    op.drop_table('projetos')
    op.drop_table('perfil_permissoes')
    op.drop_table('membros')
    op.drop_table('beneficiarios')
    op.drop_table('pessoas')
    op.drop_table('permissoes')
    op.drop_table('perfis')
    op.drop_table('contas_financeiras')
    op.drop_table('categorias_financeiras')
    op.drop_table('cargos')
    # ### end Alembic commands ###
